### ISSUE TITLE
No database connection on velocity proxy

### ISSUE THREAD

**Issue by Weltensiedler** [vergamed/BungeeOnlineTime#1]
Hey,

we are using BungeeOnlinetime with Waterfall and it works good. Now, Waterfall will no longer become updates, so we have to switch over to velocity. In the comments of the original plugin I found this github. 

We are using right now:
Velocity Velocity 3.3.0-SNAPSHOT (git-a9a31f69-b385)
BungeeOnlineTime 8.4.1

Error:
[13:54:36 INFO] [onlinetime]: Connecting to MySQL...
[13:54:36 ERROR] [onlinetime]: Error while connecting to MySQL. Disabling plugin...
[13:54:36 ERROR]: java.lang.IllegalStateException: No supported database driver present!
[13:54:36 ERROR]:       at lu.r3flexi0n.bungeeonlinetime.common.db.Database.openConnection(Database.kt:26)
[13:54:36 ERROR]:       at lu.r3flexi0n.bungeeonlinetime.velocity.VelocityOnlineTimePlugin.onEnable(VelocityOnlineTimePlugin.kt:58)
[13:54:36 ERROR]:       at lu.r3flexi0n.bungeeonlinetime.velocity.Lmbda$6.execute(Unknown Source)
[13:54:36 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[13:54:36 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[13:54:36 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[13:54:36 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:54:36 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:54:36 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Weltensiedler** [comment]
I thinks it's because we are using MariaDB as MySQL-Alternative and the implementation in your database connector is missing this option, which is a problem, becuase MariaDB is the right now the most common SQL variant.

**Comment by Weltensiedler** [comment]
Hello?

**Comment by dan28000** [comment]
do you still need this?
I forked it and fixed obvious issues just use the fat version I didn't bother with the other 2 versions
https://github.com/dan28000/BungeeOnlineTime/releases/tag/8.4.1

**Comment by itsTyrion** [comment]
I never received an email about this because, somehow, the repo got set to being not watched by myself. I'll make an update today (I started one months ago but was busy/got distracted)

**Comment by games4681** [comment]
> do you still need this? I forked it and fixed obvious issues just use the fat version I didn't bother with the other 2 versions https://github.com/dan28000/BungeeOnlineTime/releases/tag/8.4.1

Thank you

**Comment by itsTyrion** [comment]
Fixed in f73c430 / the 8.5.0 update. https://github.com/itsTyrion/BungeeOnlineTime/releases/tag/8.5.0
